---
title: "Regenerate figures for the ORA paper"
author: "Ziemann lab"
date: "`r Sys.Date()`"
output:
  html_document:
  toc: true
theme: cosmo
---

Source: https://github.com/markziemann/background/

## Introduction

Here we investigate two subtle problems with ORA.

```{bash,pull}

git pull

```

# Workflow

## Data preparation

Need to fetch some data.

```{r,maindataprep}

setwd("../dataprep")
rmarkdown::render("bulkrna1.Rmd")
rmarkdown::render("bulkrna2.Rmd")
rmarkdown::render("bulkrna3.Rmd")
rmarkdown::render("bulkrna4.Rmd")
rmarkdown::render("bulkrna5.Rmd")
rmarkdown::render("bulkrna6.Rmd")
rmarkdown::render("bulkrna7.Rmd")
setwd("../analysis")

```

## Figure 1 - the background problem

```{r,mainfig1}

rmarkdown::render("analyse_rnaseq1.Rmd")

```

## Figure 2 - the FDR problem

```{r,mainfig2}

rmarkdown::render("analyse_rnaseq2.Rmd")

```

## Figure 3 - Examining accuracy with simulated expression data

```{r,mainfig3}

setwd("sim")
rmarkdown::render("run_simpw.Rmd")
setwd("..")

```

## Figure 4 - Quantifying sensitivity in real cancer data

```{r,mainfig4}

rmarkdown::render("GSE158420_rna.Rmd")

```

## Manuscript

```{r,main_manuscript}

setwd("../manuscript")
rmarkdown::render("manuscript.Rmd")

```

# Session information

```{r,mainsession}

sessionInfo()

```
